version: '3.1'
services:
  php:
     build:
          args:
              user: www-data
              uid: 1000
          context: ./docker/php-7.2/
     container_name: php-fpm
     restart: unless-stopped
     ports:
        - 82:80

     environment:
          WWWUSER: '${WWWUSER}'
     volumes:
          - '.:/var/www/html'
     networks:
         - app
     depends_on:
         - mysql

  mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
          - ./docker/mysql:/var/lib/mysql

        networks:
            - app
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

networks:
    app:
        driver: bridge
volumes:
    appmysql:
        driver: local

